name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test Suite
    runs-on: ${{ matrix.platform }}
    
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: './src-tauri -> target'

    - name: Install system dependencies (Ubuntu)
      if: matrix.platform == 'ubuntu-20.04'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

    - name: Install dependencies
      run: bun install

    - name: Format check
      run: bun run format --check

    - name: Lint check
      run: bun run check

    - name: Type check
      run: bun run typecheck

    - name: Run unit tests
      run: bun run test:run

    - name: Rust format check
      run: cargo fmt --all --manifest-path=src-tauri/Cargo.toml -- --check

    - name: Rust clippy
      run: cargo clippy --manifest-path=src-tauri/Cargo.toml --all-targets --all-features -- -D warnings

    - name: Rust tests
      run: cargo test --manifest-path=src-tauri/Cargo.toml

    - name: Build application
      run: bun run build

  security:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install dependencies
      run: bun install

    - name: Security audit (Rust)
      run: cargo audit --manifest-path=src-tauri/Cargo.toml

    - name: Security audit (npm)
      run: bun audit

  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

    - name: Install dependencies
      run: bun install

    - name: Install Playwright
      run: bunx playwright install --with-deps

    - name: Run E2E tests
      run: bun run test:e2e